GET http://localhost:3001/api/persons

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Reard Gjoni",
  "number": "39-44-532352213"
}

###

DELETE http://localhost:3001/api/persons/69b02d72e11e0ae76f8c6409







